// Handle change
export const HANDLE_CHANGE_USERNAME = "HANDLE_CHANGE_USERNAME";
export const HANDLE_CHANGE_MAIL = "HANDLE_CHANGE_MAIL";
export const HANDLE_CHANGE_PASSWORD = "HANDLE_CHANGE_PASSWORD";
